import torch
import shap
import streamlit as st
from transformers import Pipeline
from utils import get_torch_device


@st.cache_data
def compute_prediction(text: str, _classifier: Pipeline, _explainer: shap.Explainer) -> None:
    st.session_state['text_input'] = text
    st.session_state['prediction'] = _classifier(text)
    st.session_state['shap_values'] = _explainer([text])


if __name__ == '__main__':
    import streamlit as st
    from streamlit_shap import st_shap
    from transformers import pipeline
    import os
    import shap

    ############################ SECTION 00 ###################################
    # Load AI-generatet text classification model
    model_path = os.path.abspath('model')
    classifier = pipeline(
        'text-classification',
        model=model_path,
        device=get_torch_device(debug=True),
        top_k=1,
        truncation=True,
        padding=True,
    )
    
    # Create SHAP explainer
    explainer = shap.Explainer(classifier)

    # Initialize session state
    if 'prediction' not in st.session_state:
        st.session_state['prediction'] = None
    if 'shap_values' not in st.session_state:
        st.session_state['shap_values'] = None
    if 'text_input' not in st.session_state:
        st.session_state['text_input'] = None

    ############################ SECTION 01 ###################################
    st.title("Check whether an essay has been generated by AI or not 🤖")
    st.write('\n')

    # Input text
    txt = st.text_area(
        "Enter text to check",
        value=st.session_state['text_input'],
        max_chars=2500,
        height=200,
        placeholder="Copy the text that you want to check here.",
        label_visibility="collapsed",
        on_change=lambda: compute_prediction(st.session_state['text_area'], classifier, explainer),
        key='text_area',
    )

    # Submit button
    st.write('\n')
    col1, col2, col3, col4, col5 = st.columns(5)
    if col3.button('Check text', type='primary', use_container_width=True):
        compute_prediction(txt, classifier, explainer)


    ############################ SECTION 02 ###################################
    st.write('\n')
    st.write('\n')
    prediction = st.session_state['prediction']
    shap_values = st.session_state['shap_values']

    if prediction and shap_values:
        # Display prediction result
        prob = prediction[0][0]['score']
        if prediction[0][0]['label'] == 'human': prob = 1 - prob
        st.subheader(f'There is a :blue[{round(prob * 100, 2)}%] chance that this text has been generated by an AI model.')

        # Explainable AI plots
        st_shap(shap.plots.text(shap_values[:,:,'ai']), height=300)
        st_shap(shap.plots.bar(shap_values[0, :, "ai"]))
